# UK Crime Data Analysis (Jan 2024– Dec 2025)

## Project Overview
This project performs an exploratory data analysis (EDA) of UK street-level crime data to support decision-making within a real estate context. The analysis aims to identify patterns in crime across different police force regions and provide insights into which areas may be more or less desirable for property sales.

## Stakeholder
Nadine Green – Head of Sales

## Data Source
UK Police Data: https://data.police.uk/data/

## Police Forces Selected

- Metropolitan Police Service  
- West Midlands Police  
- West Yorkshire Police  
- Thames Valley Police  
- Surrey Police

## Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

## Loading and Combining Crime Data

The raw data is stored across two folders in the project directory:
- police data 1
- police data 2

Each folder contains monthly CSV files for the selected police forces.All files are automatically loaded and combined into a single dataframe.

After loading the files, the dataset is inspected using:
- shape
- column names
- data types
- summary statistics
- sample records

In [2]:
import os
print(os.getcwd())
print(os.listdir())

/Users/thadshasivashanker/Documents/rockborne /python/crime-analysis-project/notebooks
['data_preprocessing.ipynb', '.ipynb_checkpoints', '01_data_preprocessing.ipynb']

In [3]:
base_path = "../data/raw"
print("Folder exists:", os.path.exists(base_path))
print("Folders inside raw:", os.listdir(base_path))#check if the folder exists
all_data = [] # creates an empty list 
for data_folder in os.listdir(base_path): #loop through each folder in raw folder 
    data_path = os.path.join(base_path, data_folder)
    if not os.path.isdir(data_path):
        continue
    for month_folder in os.listdir(data_path): #loop through each month folder 
        month_path = os.path.join(data_path, month_folder)
        if not os.path.isdir(month_path): #skips anything that is not a folder 
            continue
        for file in os.listdir(month_path):
            if file.endswith(".csv"):
                file_path = os.path.join(month_path, file)
                print("Loading:", file_path)
                df_temp = pd.read_csv(file_path) # reads csv file
                force_name = file.replace(".csv", "").split("-")[2:-1]
                force_name = " ".join(force_name)
                df_temp["PoliceForce"] = force_name
                all_data.append(df_temp)
df = pd.concat(all_data, ignore_index=True) #combines all the files into one dataframe

print("Data loaded successfully")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Folder exists: True
Folders inside raw: ['.DS_Store', 'police data 1', 'police data 2']
Loading: ../data/raw/police data 1/2024-09/2024-09-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-09/2024-09-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-09/2024-09-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-09/2024-09-surrey-street.csv
Loading: ../data/raw/police data 1/2024-09/2024-09-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-09/2024-09-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-07/2024-07-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-07/2024-07-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-07/2024-07-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-07/2024-07-surrey-street.csv
Loading: ../data/raw/police data 1/2024-07/2024-07-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-07/2024-07-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-06/2024-06-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-06/2024-06-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-06/2024-06-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-06/2024-06-surrey-street.csv
Loading: ../data/raw/police data 1/2024-06/2024-06-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-06/2024-06-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-01/2024-01-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-01/2024-01-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-01/2024-01-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-01/2024-01-surrey-street.csv
Loading: ../data/raw/police data 1/2024-01/2024-01-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-01/2024-01-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-08/2024-08-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-08/2024-08-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-08/2024-08-surrey-street.csv
Loading: ../data/raw/police data 1/2024-08/2024-08-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-08/2024-08-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-08/2024-08-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-06/2025-06-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-06/2025-06-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-06/2025-06-surrey-street.csv
Loading: ../data/raw/police data 1/2025-06/2025-06-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-06/2025-06-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-06/2025-06-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-01/2025-01-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-01/2025-01-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-01/2025-01-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-01/2025-01-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-01/2025-01-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-01/2025-01-surrey-street.csv
Loading: ../data/raw/police data 1/2025-08/2025-08-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-08/2025-08-surrey-street.csv
Loading: ../data/raw/police data 1/2025-08/2025-08-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-08/2025-08-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-08/2025-08-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-08/2025-08-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-09/2025-09-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-09/2025-09-surrey-street.csv
Loading: ../data/raw/police data 1/2025-09/2025-09-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-09/2025-09-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-09/2025-09-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-09/2025-09-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-07/2025-07-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-07/2025-07-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-07/2025-07-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-07/2025-07-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-07/2025-07-surrey-street.csv
Loading: ../data/raw/police data 1/2025-07/2025-07-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-12/2025-12-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-12/2025-12-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-12/2025-12-surrey-street.csv
Loading: ../data/raw/police data 1/2025-12/2025-12-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-12/2025-12-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-12/2025-12-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-12/2024-12-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-12/2024-12-surrey-street.csv
Loading: ../data/raw/police data 1/2024-12/2024-12-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-12/2024-12-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-12/2024-12-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-12/2024-12-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-04/2024-04-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-04/2024-04-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-04/2024-04-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-04/2024-04-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-04/2024-04-surrey-street.csv
Loading: ../data/raw/police data 1/2024-04/2024-04-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-03/2024-03-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-03/2024-03-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-03/2024-03-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-03/2024-03-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-03/2024-03-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-03/2024-03-surrey-street.csv
Loading: ../data/raw/police data 1/2024-02/2024-02-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-02/2024-02-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-02/2024-02-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-02/2024-02-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-02/2024-02-surrey-street.csv
Loading: ../data/raw/police data 1/2024-02/2024-02-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-05/2024-05-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-05/2024-05-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-05/2024-05-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-05/2024-05-surrey-street.csv
Loading: ../data/raw/police data 1/2024-05/2024-05-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-05/2024-05-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-02/2025-02-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-02/2025-02-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-02/2025-02-surrey-street.csv
Loading: ../data/raw/police data 1/2025-02/2025-02-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-02/2025-02-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-02/2025-02-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-05/2025-05-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-05/2025-05-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-05/2025-05-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-05/2025-05-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-05/2025-05-surrey-street.csv
Loading: ../data/raw/police data 1/2025-05/2025-05-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-04/2025-04-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-04/2025-04-metropolitan-street.csv

Loading: ../data/raw/police data 1/2025-04/2025-04-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-04/2025-04-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-04/2025-04-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-04/2025-04-surrey-street.csv
Loading: ../data/raw/police data 1/2025-03/2025-03-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-03/2025-03-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-03/2025-03-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-03/2025-03-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-03/2025-03-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-03/2025-03-surrey-street.csv
Loading: ../data/raw/police data 1/2025-10/2025-10-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-10/2025-10-surrey-street.csv
Loading: ../data/raw/police data 1/2025-10/2025-10-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-10/2025-10-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-10/2025-10-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-10/2025-10-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2025-11/2025-11-surrey-street.csv
Loading: ../data/raw/police data 1/2025-11/2025-11-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2025-11/2025-11-metropolitan-street.csv
Loading: ../data/raw/police data 1/2025-11/2025-11-west-midlands-street.csv
Loading: ../data/raw/police data 1/2025-11/2025-11-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2025-11/2025-11-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-11/2024-11-surrey-street.csv
Loading: ../data/raw/police data 1/2024-11/2024-11-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-11/2024-11-west-midlands-outcomes.csv
Loading: ../data/raw/police data 1/2024-11/2024-11-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-11/2024-11-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-11/2024-11-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-10/2024-10-surrey-street.csv
Loading: ../data/raw/police data 1/2024-10/2024-10-metropolitan-street.csv
Loading: ../data/raw/police data 1/2024-10/2024-10-west-midlands-street.csv
Loading: ../data/raw/police data 1/2024-10/2024-10-surrey-outcomes.csv
Loading: ../data/raw/police data 1/2024-10/2024-10-metropolitan-outcomes.csv
Loading: ../data/raw/police data 1/2024-10/2024-10-west-midlands-outcomes.csv
Loading: ../data/raw/police data 2/2024-09/2024-09-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-09/2024-09-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-09/2024-09-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-09/2024-09-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-07/2024-07-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-07/2024-07-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-07/2024-07-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-07/2024-07-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-06/2024-06-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-06/2024-06-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-06/2024-06-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-06/2024-06-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-01/2024-01-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-01/2024-01-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-01/2024-01-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-01/2024-01-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-08/2024-08-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-08/2024-08-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-08/2024-08-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-08/2024-08-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-06/2025-06-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-06/2025-06-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-06/2025-06-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-06/2025-06-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-01/2025-01-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-01/2025-01-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-01/2025-01-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-01/2025-01-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-08/2025-08-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-08/2025-08-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-08/2025-08-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-08/2025-08-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-09/2025-09-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-09/2025-09-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-09/2025-09-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-09/2025-09-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-07/2025-07-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-07/2025-07-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-07/2025-07-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-07/2025-07-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-12/2025-12-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-12/2025-12-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-12/2025-12-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-12/2025-12-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-12/2024-12-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-12/2024-12-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-12/2024-12-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-12/2024-12-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-04/2024-04-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-04/2024-04-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-04/2024-04-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-04/2024-04-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-03/2024-03-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-03/2024-03-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-03/2024-03-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-03/2024-03-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-02/2024-02-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-02/2024-02-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-02/2024-02-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-02/2024-02-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-05/2024-05-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-05/2024-05-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-05/2024-05-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-05/2024-05-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-02/2025-02-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-02/2025-02-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-02/2025-02-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-02/2025-02-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-05/2025-05-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-05/2025-05-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-05/2025-05-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-05/2025-05-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-04/2025-04-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-04/2025-04-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-04/2025-04-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-04/2025-04-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-03/2025-03-west-yorkshire-street.csv

Loading: ../data/raw/police data 2/2025-03/2025-03-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-03/2025-03-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-03/2025-03-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-10/2025-10-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-10/2025-10-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-10/2025-10-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2025-10/2025-10-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-11/2025-11-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2025-11/2025-11-thames-valley-street.csv
Loading: ../data/raw/police data 2/2025-11/2025-11-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2025-11/2025-11-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-11/2024-11-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-11/2024-11-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-11/2024-11-west-yorkshire-outcomes.csv
Loading: ../data/raw/police data 2/2024-11/2024-11-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-10/2024-10-west-yorkshire-street.csv
Loading: ../data/raw/police data 2/2024-10/2024-10-thames-valley-street.csv
Loading: ../data/raw/police data 2/2024-10/2024-10-thames-valley-outcomes.csv
Loading: ../data/raw/police data 2/2024-10/2024-10-west-yorkshire-outcomes.csv
Data loaded successfully
Rows: 7783098
Columns: 14

In [4]:
df.head(3)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Context
0,08fc6023710334c85a8e8b14e80cbaaf53fec6a333cf99...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.266920,51.600908,On or near Back Lane,E01000129,Barnet 024D,Suspect charged,metropolitan,NaN,NaN,NaN
1,ce990bd916ddee350f57e347ed812d162f541af02f5e2e...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.118494,51.611743,On or near Moffat Road,E01001393,Enfield 036C,Suspect charged,metropolitan,NaN,NaN,NaN
2,e9b58f3d09022c1a5270be94a724ccb3487434ed9e93f2...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.038613,51.484863,On or near Canal Approach,E01003248,Lewisham 002B,Unable to prosecute suspect,metropolitan,NaN,NaN,NaN

In [5]:
df.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Context
7783093,4d5e27d863f2647ff5f7363df560ea4948a95db15800cf...,2024-10,West Yorkshire Police,West Yorkshire Police,-1.545398,53.742379,On or near Thorpe Court,E01011492,Leeds 101B,Investigation complete; no suspect identified,west yorkshire,NaN,NaN,NaN
7783094,5138cb9c6226a1105896f455f77c5a3d98f72df63d859d...,2024-10,West Yorkshire Police,West Yorkshire Police,-1.645019,53.707140,On or near Pine Grove,E01011035,Kirklees 012B,Unable to prosecute suspect,west yorkshire,NaN,NaN,NaN
7783095,cfc0f4a7daece87d02ec571e7f8b3f45d3aae31a8c1dbd...,2024-10,West Yorkshire Police,West Yorkshire Police,-1.762385,53.794991,On or near Silsbridge Street,E01010834,Bradford 044A,Investigation complete; no suspect identified,west yorkshire,NaN,NaN,NaN
7783096,200ce09564a72045a132f2f95e3c596f35342d01bd863d...,2024-10,West Yorkshire Police,West Yorkshire Police,-1.753288,53.793041,On or near Centenary Square,E01033691,Bradford 065B,Investigation complete; no suspect identified,west yorkshire,NaN,NaN,NaN
7783097,cde2d7b5ec8f0a554459529477e3deb35c79f96e7154da...,2024-10,West Yorkshire Police,West Yorkshire Police,-1.584435,53.821211,On or near Grimthorpe Avenue,E01011435,Leeds 044A,Investigation complete; no suspect identified,west yorkshire,NaN,NaN,NaN

In [6]:
df.sample(5)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Context
5067012,728ecd7ea74d9d00977e67d8e239851a66bf7ed282bc5d...,2025-10,West Midlands Police,West Midlands Police,-1.910275,52.543532,On or near Hall End Road,E01009243,Birmingham 016B,Suspect charged,west midlands,NaN,NaN,NaN
2812208,19cac402b9f38ab06cc5ab671e9284103e66e6b5135d8d...,2024-12,Metropolitan Police Service,Metropolitan Police Service,0.146382,51.491245,On or near Gilbert Road,E01000336,Bexley 003C,NaN,metropolitan,Vehicle crime,Investigation complete; no suspect identified,NaN
2783272,6f96d5c78060bdc6979e462772ffcac28e93e8455f9b6b...,2024-12,West Midlands Police,West Midlands Police,-1.974541,52.431279,On or near Inglemere Grove,E01009505,Birmingham 101E,NaN,west midlands,Criminal damage and arson,Unable to prosecute suspect,NaN
1794733,285a89e7cba91f0eaece8edc06774b3406d093ee8c037f...,2025-08,Metropolitan Police Service,Metropolitan Police Service,-0.195093,51.455569,On or near Parking Area,E01035495,Wandsworth 018F,Investigation complete; no suspect identified,metropolitan,NaN,NaN,NaN
7016915,NaN,2024-02,West Yorkshire Police,West Yorkshire Police,-1.518892,53.810351,On or near Bexley Road,E01011677,Leeds 064D,NaN,west yorkshire,Anti-social behaviour,NaN,NaN

In [7]:
df.shape   #shows 7783098 rows and 14 columns

(7783098, 14)

In [8]:
pd.set_option('display.max_columns', 25) 
df.head(3)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Context
0,08fc6023710334c85a8e8b14e80cbaaf53fec6a333cf99...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.266920,51.600908,On or near Back Lane,E01000129,Barnet 024D,Suspect charged,metropolitan,NaN,NaN,NaN
1,ce990bd916ddee350f57e347ed812d162f541af02f5e2e...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.118494,51.611743,On or near Moffat Road,E01001393,Enfield 036C,Suspect charged,metropolitan,NaN,NaN,NaN
2,e9b58f3d09022c1a5270be94a724ccb3487434ed9e93f2...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.038613,51.484863,On or near Canal Approach,E01003248,Lewisham 002B,Unable to prosecute suspect,metropolitan,NaN,NaN,NaN

In [9]:
print(df.columns)

Index(['Crime ID', 'Month', 'Reported by', 'Falls within', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Outcome type',
       'PoliceForce', 'Crime type', 'Last outcome category', 'Context'],
      dtype='object')

In [10]:
df.dtypes

Crime ID                  object
Month                     object
Reported by               object
Falls within              object
Longitude                float64
Latitude                 float64
Location                  object
LSOA code                 object
LSOA name                 object
Outcome type              object
PoliceForce               object
Crime type                object
Last outcome category     object
Context                  float64
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7783098 entries, 0 to 7783097
Data columns (total 14 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Month                  object
 2   Reported by            object
 3   Falls within           object
 4   Longitude              float64
 5   Latitude               float64
 6   Location               object
 7   LSOA code              object
 8   LSOA name              object
 9   Outcome type           object
 10  PoliceForce            object
 11  Crime type             object
 12  Last outcome category  object
 13  Context                float64
dtypes: float64(3), object(11)
memory usage: 831.3+ MB

In [12]:
df.describe() # only for numerical values

          Longitude      Latitude  Context
count  7.748811e+06  7.748811e+06      0.0
mean  -7.321348e-01  5.201400e+01      NaN
std    7.719487e-01  8.148101e-01      NaN
min   -6.789849e+00  4.996553e+01      NaN
25%   -1.551053e+00  5.149210e+01      NaN
50%   -3.049180e-01  5.155505e+01      NaN
75%   -1.035790e-01  5.247392e+01      NaN
max    1.745418e+00  5.573572e+01      NaN

In [13]:
df['Crime ID'].nunique()

3651332

## Handling Missing Data
The next step is to identify missing values across the dataset.This helps determine which columns can be cleaned through replacement, which may need to be dropped, and which missing values are expected because of the structure of the police data.

The remaining missing values are longitude and latitude. These rows were kept because they represent a small proportion of the dataset and may still be useful for non-spatial analysis. They can be excluded later for mapping tasks if needed.

In [14]:
# True when data isn't missing 
df.notnull().head(3)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Context
0,True,True,True,True,True,True,True,True,True,True,True,False,False,False
1,True,True,True,True,True,True,True,True,True,True,True,False,False,False
2,True,True,True,True,True,True,True,True,True,True,True,False,False,False

In [15]:
# True when data is missing
df.isnull().head(3)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Context
0,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,True,True,True

In [16]:
df.isnull().sum()

Crime ID                  642267
Month                          0
Reported by                    0
Falls within                   0
Longitude                  34287
Latitude                   34287
Location                       0
LSOA code                  34289
LSOA name                  34289
Outcome type             4122443
PoliceForce                    0
Crime type               3660655
Last outcome category    4302922
Context                  7783098
dtype: int64

In [17]:
null_df = pd.DataFrame(df.isnull().sum(), columns=['Count of Nulls']) #Creating a new DF
null_df.index.name = 'Column' # Changing the Index Name
null_df.sort_values(['Count of Nulls'], ascending=False) # Sorting based on our only column name

                       Count of Nulls
Column
Context                       7783098
Last outcome category         4302922
Outcome type                  4122443
Crime type                    3660655
Crime ID                       642267
LSOA code                       34289
LSOA name                       34289
Longitude                       34287
Latitude                        34287
Month                               0
Reported by                         0
Falls within                        0
Location                            0
PoliceForce                         0

In [18]:
df.info()
df.head()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7783098 entries, 0 to 7783097
Data columns (total 14 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Month                  object
 2   Reported by            object
 3   Falls within           object
 4   Longitude              float64
 5   Latitude               float64
 6   Location               object
 7   LSOA code              object
 8   LSOA name              object
 9   Outcome type           object
 10  PoliceForce            object
 11  Crime type             object
 12  Last outcome category  object
 13  Context                float64
dtypes: float64(3), object(11)
memory usage: 831.3+ MB

          Longitude      Latitude  Context
count  7.748811e+06  7.748811e+06      0.0
mean  -7.321348e-01  5.201400e+01      NaN
std    7.719487e-01  8.148101e-01      NaN
min   -6.789849e+00  4.996553e+01      NaN
25%   -1.551053e+00  5.149210e+01      NaN
50%   -3.049180e-01  5.155505e+01      NaN
75%   -1.035790e-01  5.247392e+01      NaN
max    1.745418e+00  5.573572e+01      NaN

## Drop columns

The 'Context' column had all values missing, so it was removed from the dataset.

In [19]:
df.drop(columns=["Context"], inplace=True) #dropped context column

In [20]:
df.columns # check if 'Context' is removed

Index(['Crime ID', 'Month', 'Reported by', 'Falls within', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Outcome type',
       'PoliceForce', 'Crime type', 'Last outcome category'],
      dtype='object')

In [21]:
df["Crime ID"].fillna("Unknown", inplace=True) # Replace missing Crime ID values with unknown

In [22]:
df["Last outcome category"].fillna("Outcome unknown", inplace=True)

In [23]:
df["LSOA code"].fillna("Unknown", inplace=True) # Fill missing area identifiers with 'Unknown' 
df["LSOA name"].fillna("Unknown", inplace=True)

In [24]:
df.isnull().sum()

Crime ID                       0
Month                          0
Reported by                    0
Falls within                   0
Longitude                  34287
Latitude                   34287
Location                       0
LSOA code                      0
LSOA name                      0
Outcome type             4122443
PoliceForce                    0
Crime type               3660655
Last outcome category          0
dtype: int64

## Distinguish crime records from outcome records

The combined dataset contains both street crime records and outcome records.  Crime records contain values in 'Crime type', while outcome records primarily contain values in 'Outcome type'.
To preserve both types of information in a single dataframe:
- missing 'Outcome type' values are labelled as 'Outcome not recorded'
- missing 'Crime type' values are labelled as 'Outcome record'
- a new column, 'Record type', is created to classify each row as either 'Crime' or 'Outcome'

In [25]:
df["Crime type"].value_counts(dropna=False)

NaN                             3660655
Violence and sexual offences    1251939
Anti-social behaviour            642267
Other theft                      334922
Shoplifting                      327131
Vehicle crime                    306618
Public order                     248964
Criminal damage and arson        246217
Theft from the person            199522
Burglary                         182581
Drugs                            146450
Robbery                           90551
Other crime                       68534
Bicycle theft                     44044
Possession of weapons             32703
Name: Crime type, dtype: int64

In [26]:
df["Outcome type"].value_counts(dropna=False)

NaN                                                    4122443
Investigation complete; no suspect identified          1823369
Unable to prosecute suspect                            1345253
Suspect charged                                         301052
Local resolution                                         90429
Action to be taken by another organisation               42979
Offender given a caution                                 21579
Further investigation is not in the public interest      11466
Further action is not in the public interest             10416
Formal action is not in the public interest               7215
Offender given penalty notice                             5440
Suspect charged as part of another case                   1440
Offender given a drugs possession warning                   17
Name: Outcome type, dtype: int64

In [27]:
df[["Crime type","Outcome type"]].isnull().sum()

Crime type      3660655
Outcome type    4122443
dtype: int64

In [28]:
df.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category
0,08fc6023710334c85a8e8b14e80cbaaf53fec6a333cf99...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.266920,51.600908,On or near Back Lane,E01000129,Barnet 024D,Suspect charged,metropolitan,NaN,Outcome unknown
1,ce990bd916ddee350f57e347ed812d162f541af02f5e2e...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.118494,51.611743,On or near Moffat Road,E01001393,Enfield 036C,Suspect charged,metropolitan,NaN,Outcome unknown
2,e9b58f3d09022c1a5270be94a724ccb3487434ed9e93f2...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.038613,51.484863,On or near Canal Approach,E01003248,Lewisham 002B,Unable to prosecute suspect,metropolitan,NaN,Outcome unknown
3,b81f81f0e1447a2dc7cf34a1f827a4a3ca23f5a406c473...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.145700,51.542368,On or near Leybourne Street,E01000858,Camden 018B,Investigation complete; no suspect identified,metropolitan,NaN,Outcome unknown
4,8ba005a1df4e147bc2f59b46ddf514d7b396a7504e6e00...,2024-09,Metropolitan Police Service,Metropolitan Police Service,0.082480,51.493494,On or near Goosander Way,E01033744,Greenwich 007G,Offender given penalty notice,metropolitan,NaN,Outcome unknown

In [29]:
df["Outcome type"].fillna("Outcome not recorded", inplace=True)

In [30]:
df["Crime type"].fillna("Outcome record", inplace=True)

In [31]:
df["LSOA code"].fillna("Unknown", inplace=True)
df["LSOA name"].fillna("Unknown", inplace=True)

In [32]:
df.isnull().sum()

Crime ID                     0
Month                        0
Reported by                  0
Falls within                 0
Longitude                34287
Latitude                 34287
Location                     0
LSOA code                    0
LSOA name                    0
Outcome type                 0
PoliceForce                  0
Crime type                   0
Last outcome category        0
dtype: int64

In [34]:
crime_df=df.copy()
crime_df.head()
crime_df.shape

(7783098, 13)

In [35]:
crime_df.isnull().sum().sort_values(ascending=False) #checking missing values again

Longitude                34287
Latitude                 34287
Crime ID                     0
Month                        0
Reported by                  0
Falls within                 0
Location                     0
LSOA code                    0
LSOA name                    0
Outcome type                 0
PoliceForce                  0
Crime type                   0
Last outcome category        0
dtype: int64

In [36]:
df["Record type"] = np.where(df["Crime type"] == "Outcome record", "Outcome", "Crime")
df["Record type"].value_counts()

Crime      4122443
Outcome    3660655
Name: Record type, dtype: int64

In [37]:
df[df["Record type"] == "Crime"]["Crime type"].value_counts().head() # crime types

Violence and sexual offences    1251939
Anti-social behaviour            642267
Other theft                      334922
Shoplifting                      327131
Vehicle crime                    306618
Name: Crime type, dtype: int64

In [38]:
df[df["Record type"] == "Outcome"]["Outcome type"].value_counts().head() #outcome categories

Investigation complete; no suspect identified    1823369
Unable to prosecute suspect                      1345253
Suspect charged                                   301052
Local resolution                                   90429
Action to be taken by another organisation         42979
Name: Outcome type, dtype: int64

In [39]:
df.isnull().sum()

Crime ID                     0
Month                        0
Reported by                  0
Falls within                 0
Longitude                34287
Latitude                 34287
Location                     0
LSOA code                    0
LSOA name                    0
Outcome type                 0
PoliceForce                  0
Crime type                   0
Last outcome category        0
Record type                  0
dtype: int64

## Looking at duplicates
Duplicate rows may occur after combining mutliple files.They were identified and removed to avoid doible counting during the analysis

In [40]:
df.duplicated().sum()

493379

In [41]:
df[df.duplicated()].head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Record type
43,75d9d1808e28e31e26856f641f710fbb8294d0ca816afb...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.167143,51.649642,On or near Margaret Road,E01000171,Barnet 006B,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome
183,30a61f12662c551c5bd5528e4e2bf5134f524b383c5989...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.192301,51.362270,On or near Shopping Area,E01034156,Sutton 012G,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome
195,7962351508df1eacbfc0b8741b8957907041ea61a93a85...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.025684,51.435384,On or near Grangemill Way,E01003196,Lewisham 029D,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome
205,94a5ef592dcb072cba037740bdac0d32ec689c3093bab8...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.112721,51.603629,On or near Portree Close,E01001971,Haringey 001B,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome
225,41e01a5546457ebf6f17aef26110dbc015691cd0a5954a...,2024-09,Metropolitan Police Service,Metropolitan Police Service,-0.094942,51.429264,On or near St Denis Road,E01003065,Lambeth 031A,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome

In [42]:
df[df.duplicated(keep=False)].sort_values(
    by=["Crime ID", "Month"]).head(20)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type,PoliceForce,Crime type,Last outcome category,Record type
2160311,0000ecd99983371afdac103fe9d8fab2deb7ad619eaa2d...,2025-09,Metropolitan Police Service,Metropolitan Police Service,-0.081434,51.578473,On or near Bushey Road,E01002054,Haringey 032B,Unable to prosecute suspect,metropolitan,Outcome record,Outcome unknown,Outcome
2160312,0000ecd99983371afdac103fe9d8fab2deb7ad619eaa2d...,2025-09,Metropolitan Police Service,Metropolitan Police Service,-0.081434,51.578473,On or near Bushey Road,E01002054,Haringey 032B,Unable to prosecute suspect,metropolitan,Outcome record,Outcome unknown,Outcome
5899532,0001045a278d836e584d340409a69d9babc8348ffd5836...,2024-10,West Midlands Police,West Midlands Police,-2.112513,52.603223,On or near Burbage Close,E01010480,Wolverhampton 011C,Suspect charged,west midlands,Outcome record,Outcome unknown,Outcome
5899533,0001045a278d836e584d340409a69d9babc8348ffd5836...,2024-10,West Midlands Police,West Midlands Police,-2.112513,52.603223,On or near Burbage Close,E01010480,Wolverhampton 011C,Suspect charged,west midlands,Outcome record,Outcome unknown,Outcome
4042382,00027eda95e6d3618afe1c619aac0883d127d151279ecb...,2025-02,Metropolitan Police Service,Metropolitan Police Service,-0.106345,51.520463,On or near Further/Higher Educational Building,E01000916,Camden 027B,Investigation complete; no suspect identified,metropolitan,Outcome record,Outcome unknown,Outcome
4042383,00027eda95e6d3618afe1c619aac0883d127d151279ecb...,2025-02,Metropolitan Police Service,Metropolitan Police Service,-0.106345,51.520463,On or near Further/Higher Educational Building,E01000916,Camden 027B,Investigation complete; no suspect identified,metropolitan,Outcome record,Outcome unknown,Outcome
1749407,000287deec7bccda853623ad711ee926785372ec72d0c2...,2025-08,Metropolitan Police Service,Metropolitan Police Service,-0.031992,51.399411,On or near Beck Way,E01000773,Bromley 024B,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome
1749408,000287deec7bccda853623ad711ee926785372ec72d0c2...,2025-08,Metropolitan Police Service,Metropolitan Police Service,-0.031992,51.399411,On or near Beck Way,E01000773,Bromley 024B,Suspect charged,metropolitan,Outcome record,Outcome unknown,Outcome
1649657,0002c9658c7c025dc505c5f30dee7e9d132da1aea19f33...,2025-01,Metropolitan Police Service,Metropolitan Police Service,-0.081433,51.534976,On or near Hobbs Place,E01001755,Hackney 025D,Investigation complete; no suspect identified,metropolitan,Outcome record,Outcome unknown,Outcome
1692757,0002c9658c7c025dc505c5f30dee7e9d132da1aea19f33...,2025-01,Metropolitan Police Service,Metropolitan Police Service,-0.081433,51.534976,On or near Hobbs Place,E01001755,Hackney 025D,Investigation complete; no suspect identified,metropolitan,Outcome record,Outcome unknown,Outcome
7541170,000319f84b2491a261f8317a2a778fdf3035e7985024be...,2025-11,Thames Valley Police,Thames Valley Police,-0.974514,51.467665,On or near Church Street,E01016364,Reading 003A,Suspect charged,thames valley,Outcome record,Outcome unknown,Outcome
7541171,000319f84b2491a261f8317a2a778fdf3035e7985024be...,2025-11,Thames Valley Police,Thames Valley Police,-0.974514,51.467665,On or near Church Street,E01016364,Reading 003A,Suspect charged,thames valley,Outcome record,Outcome unknown,Outcome
3289147,000342d0eab3cf619eba5f376199589b9fbb3660d3dce7...,2024-03,Metropolitan Police Service,Metropolitan Police Service,-0.137530,51.523129,On or near Midford Place,E01035711,Camden 026E,Investigation complete; no suspect identified,metropolitan,Outcome record,Outcome unknown,Outcome
3311957,000342d0eab3cf619eba5f376199589b9fbb3660d3dce7...,2024-03,Metropolitan Police Service,Metropolitan Police Service,-0.137530,51.523129,On or near Midford Place,E01035711,Camden 026E,Investigation complete; no suspect identified,metropolitan,Outcome record,Outcome unknown,Outcome
3740640,000361d829c069b0bcc20debc3152c9c1e9bec087f5cb1...,2024-05,West Midlands Police,West Midlands Police,-1.957857,52.607467,On or near Holme Way,E01010322,Walsall 016B,Suspect charged,west midlands,Outcome record,Outcome unknown,Outcome
3740641,000361d829c069b0bcc20debc3152c9c1e9bec087f5cb1...,2024-05,West Midlands Police,West Midlands Police,-1.957857,52.607467,On or near Holme Way,E01010322,Walsall 016B,Suspect charged,west midlands,Outcome record,Outcome unknown,Outcome
470640,00037579e9a8b18f302263c26abf4ee732cdd0b5b548d9...,2024-07,Metropolitan Police Service,Metropolitan Police Service,0.043146,51.383754,On or near Link Way,E01000661,Bromley 026A,Unable to prosecute suspect,metropolitan,Outcome record,Outcome unknown,Outcome
470641,00037579e9a8b18f302263c26abf4ee732cdd0b5b548d9...,2024-07,Metropolitan Police Service,Metropolitan Police Service,0.043146,51.383754,On or near Link Way,E01000661,Bromley 026A,Unable to prosecute suspect,metropolitan,Outcome record,Outcome unknown,Outcome
3130607,00037f62cb47b72c543bf305d0fda0bdfcaeb2161f81bf...,2024-04,Metropolitan Police Service,Metropolitan Police Service,-0.149193,51.514564,On or near Stratford Place,E01004714,Westminster 011B,Unable to prosecute suspect,metropolitan,Outcome record,Outcome unknown,Outcome
3195058,00037f62cb47b72c543bf305d0fda0bdfcaeb2161f81bf...,2024-04,Metropolitan Police Service,Metropolitan Police Service,-0.149193,51.514564,On or near Stratford Place,E01004714,Westminster 011B,Unable to prosecute suspect,metropolitan,Outcome record,Outcome unknown,Outcome

In [43]:
df=df.drop_duplicates() # Remove exact duplicate rows
df.duplicated().sum()

0

In [44]:
df.shape

(7289719, 14)

In [51]:
df["Month"] = pd.to_datetime(df["Month"]) # Convert Month to datetime format so it can be used for time-based analyssi

/var/folders/5w/knqyy8xj7dq0t4lkd18zgplr0000gn/T/ipykernel_99626/3883231994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"] = pd.to_datetime(df["Month"]) # Convert Month to datetime format so it can be used for time-based analyssi

In [46]:
df.dtypes

Crime ID                         object
Month                    datetime64[ns]
Reported by                      object
Falls within                     object
Longitude                       float64
Latitude                        float64
Location                         object
LSOA code                        object
LSOA name                        object
Outcome type                     object
PoliceForce                      object
Crime type                       object
Last outcome category            object
Record type                      object
dtype: object

## Final check of cleaned dataset

In [47]:
print("Final shape:", df.shape) # final check of data before EDA
print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False))
print("\nDuplicate rows:", df.duplicated().sum())
print("\nData types:")
print(df.dtypes)
print("\nRecord type counts:")
print(df["Record type"].value_counts())

Final shape: (7289719, 14)

Missing values:
Longitude                32830
Latitude                 32830
Crime ID                     0
Month                        0
Reported by                  0
Falls within                 0
Location                     0
LSOA code                    0
LSOA name                    0
Outcome type                 0
PoliceForce                  0
Crime type                   0
Last outcome category        0
Record type                  0
dtype: int64

Duplicate rows: 0

Data types:
Crime ID                         object
Month                    datetime64[ns]
Reported by                      object
Falls within                     object
Longitude                       float64
Latitude                        float64
Location                         object
LSOA code                        object
LSOA name                        object
Outcome type                     object
PoliceForce                      object
Crime type                       object
Last outcome category            object
Record type                      object
dtype: object

Record type counts:
Crime      3867981
Outcome    3421738
Name: Record type, dtype: int64

In [48]:
crime_only_df = df[df["Record type"] == "Crime"].copy()
outcome_only_df = df[df["Record type"] == "Outcome"].copy()

print("Crime records:", crime_only_df.shape)
print("Outcome records:", outcome_only_df.shape)

Crime records: (3867981, 14)
Outcome records: (3421738, 14)

In [50]:
crime_only_df.describe()

          Longitude      Latitude
count  3.851562e+06  3.851562e+06
mean  -7.492316e-01  5.203108e+01
std    7.732134e-01  8.271226e-01
min   -6.789849e+00  4.996553e+01
25%   -1.563749e+00  5.149216e+01
50%   -3.326170e-01  5.155785e+01
75%   -1.064380e-01  5.247808e+01
max    1.745418e+00  5.573572e+01

### Verifying the Saved Dataset

After saving the cleaned dataset, it was loaded into the EDA notebook for analysis. The dataset size initially appeared different from the preprocessing output. 

After checking the saved file path and dataset structure, it was confirmed that the dataset had been saved correctly. The difference occurred because the working dataframe had been filtered during the analysis. 

The cleaned dataset was therefore reloaded to ensure the EDA was performed using the full dataset produced during preprocessing.

In [52]:
import os
output_path = "../data/processed/cleaned_crime_data.csv"
crime_df.to_csv(output_path, index=False)
print(f"Cleaned dataset saved to: {output_path}")

Cleaned dataset saved to: ../data/processed/cleaned_crime_data.csv

In [53]:
os.listdir("../data/processed")

['cleaned_crime_data.csv']

In [54]:
df.shape

(7289719, 14)

In [55]:
df.to_csv("../data/processed/cleaned_crime_data.csv", index=False)

In [57]:
df.shape

(7289719, 14)

In [61]:
print(df.shape)
print(df["Record type"].value_counts())
print(df.columns.tolist())

(7289719, 14)
Crime      3867981
Outcome    3421738
Name: Record type, dtype: int64
['Crime ID', 'Month', 'Reported by', 'Falls within', 'Longitude', 'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Outcome type', 'PoliceForce', 'Crime type', 'Last outcome category', 'Record type']

In [62]:
df.to_csv("../data/processed/cleaned_crime_data.csv", index=False)
print("saved")

saved

In [63]:
import os
print(os.path.abspath("../data/processed/cleaned_crime_data.csv"))
print(os.path.exists("../data/processed/cleaned_crime_data.csv"))

/Users/thadshasivashanker/Documents/rockborne /python/crime-analysis-project/data/processed/cleaned_crime_data.csv
True

In [64]:
final_df = df.copy()
print(final_df.shape)
print(final_df["Record type"].value_counts())
final_df.to_csv("../data/processed/cleaned_crime_data.csv", index=False)

(7289719, 14)
Crime      3867981
Outcome    3421738
Name: Record type, dtype: int64